spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commerce?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform:  org.hibernate.dialect.MySQL8Dialect
    open-in-view: false