server:
  port: 8081

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    root: info

apis:
  product-graphql-api:
    url: http://localhost:8083/graphql
  order-api:
    url: http://localhost:9090/providers/order-api/v1/orders
